server:
  port: 80

# 网关名称
spring:
  application:
    name: zuul-service

# 服务注册地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:7000/eureka

# 默认服务读取eureka注册服务列表 默认间隔30秒

# 配置网关反向代理
zuul:
  routes:
    api-a:
      # 以 /api-member/访问转发到会员服务
      path: /api-member/**
      serviceId: api-member-service
    api-b:
      # 以 /api-order/访问转发到订单服务
      path: /api-order/**
      serviceId: order-server
