server:
  port: 7000 # 配置服务端口

# 如果部署集群需要保持名字相同
spring:
  application:
    name: eureka-server

eureka:
  instance:
    # 注册中心ip地址
    hostname: 127.0.0.1
  client:
    register-with-eureka: false # 是否需要将自己注册到注册中心(注册中心集群需要设置为true)，默认为true。因为自己是为注册中心，所以不需要自己注册自己
    fetch-registry: false # 是否需要搜索服务信息（是否启用注册服务信息），因为这是一个单节点的EurekaServer，不需要同步其他的EurekaServer节点的数据，所以设置为false；因为自己是为注册中心，不需要检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7000/eureka/ # 配置eureka服务器地址
  server:
    # 测试时关闭自我保护机制，保证不可用服务及时踢出
    enable-self-preservation: false
    # 剔除失效服务间隔
    eviction-interval-timer-in-ms: 10000